/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Clientes: typeof import('./src/components/home/Clientes.vue')['default']
    Facturas: typeof import('./src/components/home/Facturas.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    NavigationDrawer: typeof import('./src/components/layout/NavigationDrawer.vue')['default']
    Polizas: typeof import('./src/components/home/Polizas.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Servicios: typeof import('./src/components/home/Servicios.vue')['default']
  }
}
