/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/home': RouteRecordInfo<'/home', '/home', Record<never, never>, Record<never, never>>,
    '/home/': RouteRecordInfo<'/home/', '/home', Record<never, never>, Record<never, never>>,
    '/home/clientes': RouteRecordInfo<'/home/clientes', '/home/clientes', Record<never, never>, Record<never, never>>,
    '/home/facturas': RouteRecordInfo<'/home/facturas', '/home/facturas', Record<never, never>, Record<never, never>>,
    '/home/polizas': RouteRecordInfo<'/home/polizas', '/home/polizas', Record<never, never>, Record<never, never>>,
    '/home/servicios': RouteRecordInfo<'/home/servicios', '/home/servicios', Record<never, never>, Record<never, never>>,
  }
}
